spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdatabase
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  main:
    banner-mode: off

rsa:
  rsa-private-key: classpath:certs/private.pem
  rsa-public-key: classpath:certs/public.pem